/* Create a table called "buildings" that has the following attributes to it:

name, the full name of the building, which is a string of 80 characters
shortname, a shortened reference to the building name, which is a string of 10 characters
id, an integer primary key that is auto-generated by the database (that is to say, you do not specify the id when you insert values into the table)
In addition, make sure the following constraints are enforced:

name can never be NULL
shortname must always be unique
Buildings also have rooms, so create a second table, called "rooms" that has the following:

number, an integer identifier for the room
buildingid, an integer referring to the buildings primary key
seating, an integer reflecting the number of open seats in the room */

CREATE TABLE buildings(
  id INTEGER PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  shortname VARCHAR(10) UNIQUE
);

CREATE TABLE rooms(
  buildingid INTEGER,
  number INTEGER,
  seating INTEGER,
  FOREIGN KEY(buildingid) REFERENCES buildings(id)
);

INSERT INTO buildings(name, shortname) VALUES('Mary Gates Hall', 'MGH');
INSERT INTO buildings(name, shortname) VALUES('Savery Hall', 'Sav');
INSERT INTO rooms VALUES((SELECT id FROM buildings WHERE name='Mary Gates Hall'), 300, 20);
INSERT INTO rooms VALUES((SELECT id FROM buildings WHERE name='Savery Hall'), 168, 35);
